### ISSUE TITLE
java.lang.IllegalStateException: Duplicate keys are impossible when collecting from a map

### ISSUE THREAD

**Issue by 0xibram** [anvilsecure/aws-sigv4#10]
Hi,
The plugin keeps failing when signing a message. Here is the stack trace:

```
java.lang.IllegalStateException: Duplicate keys are impossible when collecting from a map
	at software.amazon.awssdk.utils.CollectionUtils.throwIllegalStateException(CollectionUtils.java:134)
	at java.base/java.util.TreeMap.mergeValue(TreeMap.java:843)
	at java.base/java.util.TreeMap.merge(TreeMap.java:718)
	at java.base/java.util.stream.Collectors.lambda$toMap$68(Collectors.java:1658)
	at java.base/java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)
	at java.base/java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1837)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at software.amazon.awssdk.utils.CollectionUtils.deepUnmodifiableMap(CollectionUtils.java:108)
	at software.amazon.awssdk.http.DefaultSdkHttpFullRequest.<init>(DefaultSdkHttpFullRequest.java:58)
	at software.amazon.awssdk.http.DefaultSdkHttpFullRequest.<init>(DefaultSdkHttpFullRequest.java:41)
	at software.amazon.awssdk.http.DefaultSdkHttpFullRequest$Builder.build(DefaultSdkHttpFullRequest.java:331)
	at software.amazon.awssdk.http.DefaultSdkHttpFullRequest$Builder.build(DefaultSdkHttpFullRequest.java:170)
	at software.amazon.awssdk.auth.signer.internal.BaseAws4Signer.sign(BaseAws4Signer.java:47)
	at burp.BurpExtender.signRequest(BurpExtender.java:1509)
	at burp.BurpExtender.processHttpMessage(BurpExtender.java:1680)
	at burp.ani.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
```

**Comment by UserExistsError** [comment]
I think you are experiencing the issue that was fixed in b60f89a6fdc7bb8ea9e665f51999fd62c2b9daca. This fix is not present in the BApp store version of the extension so it will need to be built. Please let me know if that fixes your problem.

**Comment by 3lpsy** [comment]
I believe this happens when the "host" header is lowercase (or possibly another header). Try naming it to "Host" (or play around with case of any other headers). I believe there's a case sensitivity mismatch somewhere.

**Comment by UserExistsError** [comment]
I was able to reproduce the error with the BApp store version of the extension but not with the one built from the `improved-config` branch. However, I did notice that a lowercase "host" header resulted in an invalid signature response in the latest build so I've addressed this in https://github.com/anvilventures/aws-sigv4/commit/89c7acfe5fb5e8eb881f9b4138e006734d71d06a.

I don't fully understand the original issue but it seems the awssdk errors out when attempting to add a header (such as "Host") if a case-insensitive matching header is passed in by the caller. I encountered this before which is why you can see that other headers are removed before signing, just above the latest fix.

So, until I can update the BApp store version of the extension, please build from the `improved-config` branch.

**Comment by UserExistsError** [comment]
The host header fix is in the BApp store: https://github.com/PortSwigger/aws-sigv4/pull/1
